# Generated by Django 2.2.12 on 2022-08-07 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Experiance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.TextField()),
                ('company_name', models.TextField()),
                ('joining_date', models.TextField()),
                ('leaving_date', models.TextField()),
                ('desc', models.TextField()),
            ],
        ),
    ]
