# Generated by Django 2.2.12 on 2022-08-07 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0002_experiance_work'),
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('date', models.TextField()),
                ('desc', models.TextField()),
                ('status', models.TextField()),
            ],
        ),
    ]
