# Generated by Django 2.2.12 on 2022-08-07 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0004_intern'),
    ]

    operations = [
        migrations.AddField(
            model_name='intern',
            name='company',
            field=models.TextField(),
            ),
    ]
