# Generated by Django 2.2.12 on 2022-08-07 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0005_intern_company'),
    ]

    operations = [
        migrations.RenameField(
            model_name='intern',
            old_name='company',
            new_name='comp',
        ),
    ]
