# Generated by Django 2.2.12 on 2022-08-07 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0006_auto_20220807_1357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intern',
            name='comp',
            field=models.TextField(),
        ),
    ]
