# Generated by Django 2.2.12 on 2022-08-07 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0007_auto_20220807_1358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intern',
            name='comp',
            field=models.TextField(default='abc'),
        ),
    ]
