# Generated by Django 2.2.12 on 2022-08-07 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0009_auto_20220807_1400'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='intern',
            name='comp',
        ),
    ]
