# Generated by Django 2.2.12 on 2022-08-07 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0010_remove_intern_comp'),
    ]

    operations = [
        migrations.AddField(
            model_name='intern',
            name='comny',
            field=models.TextField(default='abc'),
            preserve_default=False,
        ),
    ]
