# Generated by Django 3.2.12 on 2022-08-27 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0012_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='upload',
            field=models.FileField(default='None', upload_to='media'),
            preserve_default=False,
        ),
    ]
